import "./globals.css";
import Link from "next/link";
import blogs from "@/fixtures/blogs.js";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pages = [
  {
    label: "Home",
    href: "/",
  },
  {
    label: "About",
    href: "/about",
  },
  {
    label: "Contact",
    href: "/contact",
  },
  {
    label: "Blog",
    href: "/blog",
  },
  ...blogs.map(({ title, slug }) => ({
    label: title,
    href: `/blog/${slug}`,
  })),
];

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" h-full w-full">
      <body className={`antialiased flex flex-col h-full w-full`}>
        <nav className="container mx-auto mb-6 py-6">
          <ul className="flex items-center -mx-2">
            {pages.map((page, index) => (
              <li key={index} className="mx-2">
                <Link href={page.href}>{page.label}</Link>
              </li>
            ))}
          </ul>
        </nav>
        <div className="container mx-auto  flex-1">{children}</div>
        <div className="py-6 container mx-auto">Footer</div>
      </body>
    </html>
  );
}
